name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ steps.set_tag.outputs.date }}

    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "melihafsar" --password-stdin
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/melihafsar/internship-frontend:${{ env.IMAGE_TAG }}
    - name: Push the Docker image
      run: docker push ghcr.io/melihafsar/internship-frontend:${{ env.IMAGE_TAG }}
    
